### ISSUE TITLE
Make certain dependencies optional

### ISSUE THREAD

**Issue by cloudhead** [cyphernet-dao/rust-cyphernet#6]
It would be nice if `eidolon-auth` and `sha3` were made optional, so that we don't have to depend on them if we don't use them. I'm not sure where `sha3` is currently used actually, or if it's needed somewhere I'm not realizing.

`sha3` is currently being pulled by `cypheraddr`
`eidolon-auth` is being pulled by `cyphernet`

**Comment by dr-orlovsky** [comment]
`sha3` is used by Tor support - and it is already an optional requirement at the level of both `cypheraddr` and main `cyphernet` crate (both `sha3` and `tor` features must be set off).

`eidolon` is now optional with #8
